"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_mocha"

add_newline = false

format = '$directory$git_branch$git_status$character'
right_format = '$golang$python$nodejs$kubernetes$aws'

[directory]
truncation_length = 1
format = '[$path ]($style)'
style = 'bold blue'

[git_branch]
symbol = ' '
format = '[$symbol$branch ]($style)'
style = 'bold red'

[git_status]
format = '([\[$all_status$ahead_behind\] ]($style))'
style = 'bold red'
ahead = '+'
behind = '-'
stashed = ''
modified = 'M'
staged = 'S'
renamed = 'R'
deleted = 'D'
typechanged = 'T'

[character]
success_symbol = '[\$](green)'
error_symbol = '[\$](red)'
vimcmd_symbol = '[\$](blue)'

[golang]
symbol = '󰟓 '
format = '[$symbol($version )]($style)'
style = 'bold sky'

[python]
symbol = '󰌠 '
format = '[$symbol($version )]($style)'
style = 'bold yellow'

[nodejs]
format = '[$symbol($version )]($style)'
style = 'bold green'

[kubernetes]
disabled = false
symbol = '󱃾'
format = '[$symbol $context/$namespace]($style)'
style = '#326ce5'

[aws]
symbol = '󰸏'
format = '[$symbol $region]($style)'
style = '#ff9900'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
